--- 
title: "Metod i kriminologi"
author: "Kriminolog grupp vid Umeå universitet"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This is a minimal example of using the bookdown package to write a book.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::gitbook,
link-citations: true
github-repo: "rstudio/bookdown-demo"
---

# Introduktion 

Vällkommen till **Kriminologi A**.

Vi bygger upp innehållet i den här boken över tid och uppdaterar den allt eftersom för att ge den bästa möjliga introduktionen till kvantitativa metoder inom kriminologi som vi kan. Vi har börjat använda R (jämfört med andra som SPSS, STATA eller Jamovi) i dessa kriminologikurser av flera anledningar. 
För det första tror vi att R är mer mångsidigt, vilket gör det möjligt för studenter att lära sig att använda olika statistiska verktyg som finns tillgängliga i andra program, samtidigt som de har möjlighet att tillåta andra typer av analyser som är relevanta för kriminologi (till exempel rumsliga analyser eller nätverksanalyser) som inte är tillgängliga i andra program. För det andra används R i större utsträckning inom både akademisk forskning och andra yrkesområden av intresse för studenter som studerar kriminologi, t.ex. arbete i lokala och nationella myndigheter. För det tredje är R gratis och open access, vilket innebär att det inte kommer att kosta dem pengar i framtiden att ge studenterna en introduktion till detta verktyg. För det fjärde tror vi att det finns pedagogiska fördelar som studenter får när de tvingas tänka på data och analyser med kod istället för peka-och-klicka-program. Ett exempel på detta är att kommandoraden för en linjär regressionsmodell i R är mycket lik den faktiska formeln, vilket innebär att eleverna är mer benägna att komma ihåg varje komponent i formeln tillsammans med deras betydelse. 
Den tänkta användningen av denna bok är att paras ihop med kriminologikurserna vid Umeå universitet och de exempel vi använder är från föreläsningarna och workshopparna i den kursen. Där det är möjligt försöker vi tillhandahålla textinformation för att förklara begreppen och hur de tillämpas i R-miljön utan att boken blir för "texttung". 



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
